# Generated by Django 5.2.17 on 2026-09-23 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YnabConnection',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ynab', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('token_encrypted', models.TextField()),
                ('plan_id', models.CharField(blank=True, default='', max_length=64)),
                ('plan_name', models.CharField(blank=True, default='', max_length=200)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'YNAB connection',
                'verbose_name_plural': 'YNAB connections',
            },
        ),
        migrations.CreateModel(
            name='ScenarioAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('last_pulled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ynab_anchor', to='budgets.scenario')),
            ],
            options={
                'verbose_name': 'scenario anchor',
            },
        ),
        migrations.CreateModel(
            name='AnchoredCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ynab_category_id', models.CharField(max_length=64)),
                ('name_cache', models.CharField(blank=True, default='', max_length=200)),
                ('group_name_cache', models.CharField(blank=True, default='', max_length=200)),
                ('budgeted_milli', models.BigIntegerField(default=0)),
                ('missing', models.BooleanField(default=False)),
                ('anchor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ynab.scenarioanchor')),
            ],
            options={
                'verbose_name_plural': 'anchored categories',
                'ordering': ['group_name_cache', 'name_cache'],
                'constraints': [models.UniqueConstraint(fields=('anchor', 'ynab_category_id'), name='unique_category_per_anchor')],
            },
        ),
    ]
